In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer

In [2]:
X = [[1, 2], [3, np.nan], [7, 6]]
X

[[1, 2], [3, nan], [7, 6]]

In [3]:
imputer = SimpleImputer(strategy='mean')
X_t1 = imputer.fit_transform(X)
X_t1

array([[1., 2.],
       [3., 4.],
       [7., 6.]])

In [ ]:
data = pd.DataFrame({
    'RAM(GB)' : [3,np.nan,6,8],
    'PRICE' : [7000, 12000, np.nan, 24000]
})
imputer = SimpleImputer(strategy='mean')
# imputer = SimpleImputer(strategy='most_frequent')
X_t2 = imputer.fit_transform(data)
X_t2

array([[3.0e+00, 7.0e+03],
       [3.0e+00, 1.2e+04],
       [6.0e+00, 7.0e+03],
       [8.0e+00, 2.4e+04]])

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
df = pd.DataFrame({
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Chennai']
})
df

city
0    Delhi
1   Mumbai
2    Delhi
3  Chennai

In [28]:
ohe = OneHotEncoder(sparse_output=False)
df_t = ohe.fit_transform(df)
print(df_t)
# print(sorted(df.values))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [29]:
print(df_t)
print(ohe.get_feature_names_out())

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
['city_Chennai' 'city_Delhi' 'city_Mumbai']


In [31]:
from sklearn.preprocessing import LabelEncoder

labels = ['spam', 'ham', 'ham', 'spam','Invalid email']
le = LabelEncoder()
encoded = le.fit_transform(labels)

print(encoded)

[2 1 1 2 0]


In [41]:
from sklearn.preprocessing import MinMaxScaler

X = [[10], [10], [20], [30]]

scaler = StandardScaler()
scaled = scaler.fit_transform(X)

print(scaled)

[[-0.90453403]
 [-0.90453403]
 [ 0.30151134]
 [ 1.50755672]]


In [83]:
df = pd.DataFrame({
    'age': [20, None, 30],
    'gender': ['M', 'F', 'M'],
    'income': [40000, 50000, None]
})
df

age gender   income
0  20.0      M  40000.0
1   NaN      F  50000.0
2  30.0      M      NaN

In [84]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df_imp = imputer.fit_transform(df.drop(columns=['gender']))
df[['age','income']] = df_imp
print(df)

    age gender   income
0  20.0      M  40000.0
1  25.0      F  50000.0
2  30.0      M  45000.0


In [85]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
# from sklearn.compose import ColumnTransformer

In [93]:
print(df)
print(df.info())
print(df.describe())


    age gender   income
0  20.0      M  40000.0
1  25.0      F  50000.0
2  30.0      M  45000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     3 non-null      float64
 1   gender  3 non-null      object 
 2   income  3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 200.0+ bytes
None
        age   income
count   3.0      3.0
mean   25.0  45000.0
std     5.0   5000.0
min    20.0  40000.0
25%    22.5  42500.0
50%    25.0  45000.0
75%    27.5  47500.0
max    30.0  50000.0


In [107]:
ohe = OneHotEncoder(sparse_output=False)
col_gender = ohe.fit_transform(df[['gender']])
print(col_gender)

[[0. 1.]
 [1. 0.]
 [0. 1.]]


In [108]:
print(df)

    age gender   income
0  20.0      M  40000.0
1  25.0      F  50000.0
2  30.0      M  45000.0


In [111]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df[['income']])
df[['income']] = df_scaled

In [112]:
print(df)

    age gender    income
0  20.0      M -1.224745
1  25.0      F  1.224745
2  30.0      M  0.000000
